# Day 7

### How to code a simple linear regression

In [1]:
import numpy as np

In [3]:
import pandas as pd

In [5]:
x = [1, 2, 3, 4, 5]
y = [3, 6, 8, 7, 4]

foo = pd.DataFrame({'X': x, 'Y': y})

In [7]:
foo

X  Y
0  1  3
1  2  6
2  3  8
3  4  7
4  5  4

In [9]:
x_mean = foo['X'].mean()
x_mean

3.0

In [11]:
y_mean = foo['Y'].mean()
y_mean

5.6

In [13]:
x_mean_diff = x - x_mean
x_mean_diff

array([-2., -1.,  0.,  1.,  2.])

In [15]:
y_mean_diff = y - y_mean
y_mean_diff

array([-2.6,  0.4,  2.4,  1.4, -1.6])

In [19]:
x_mean_diff_sqr = np.square(x_mean_diff)
x_mean_diff_sqr

array([4., 1., 0., 1., 4.])

In [23]:
m = (x_mean_diff.sum() * y_mean_diff.sum()) / (x_mean_diff_sqr).sum()
m

0.0

In [27]:
c = np.absolute(m*x_mean - y_mean)
c

5.6