In [5]:
import numpy as np

### What are the properties of a matrix?
##### The properties of matrices are in:
- Matrix Addition
- Scalar Multiplication of Matrix
- Matrix Multiplication
- Transponse Matrix
- And many more

***
### We'll be now reading about the basics of a popular library in Python named 'NumPy'.
#### The most common thing we'll end up doing using 'NumPy' is using arrays
#### We create arrays in NumPy by following method:
***

In [7]:
a = np.array([1, 2])

In [9]:
a

array([1, 2])

---
#### We can check it's type.

In [12]:
type(a)

numpy.ndarray

---
#### But using dtype we get to know what kind of data does it holds.

In [18]:
a.dtype

dtype('int32')

---
#### We can also get the amount of values we have stored in an array.

In [46]:
a.size

2

#### Since we only had two values in it we displayed '2'.

---
#### We can also we the shape of the array

In [32]:
a.shape

(2,)

#### Here the 2 before the comma represents the x demension of the array as it is only a single demensional array.
##### Note: We'll look into this fuction with multiple demensions later on.

---
#### A better way to understand this is by using '.ndim' inbuilt function.

In [25]:
a.ndim

1

#### Just one singular demension

---
## Let's now experiment we two demensional arrays

In [35]:
b = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]], dtype='int')

In [37]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

---
#### We can use the same functions that we used in above for this two demensional array too.

In [49]:
print(type(b))

<class 'numpy.ndarray'>


In [39]:
b.dtype

dtype('int32')

In [41]:
b.shape

(3, 3)

#### WE can see that the shape now has 'x' and 'y' demensions to display.

In [43]:
b.size

9

In [51]:
b.ndim

2

---
## Let's now experiment we three demensional arrays

In [56]:
c = np.array([[[ 1,  2,  3], 
                [4, 5, 6], 
                [7, 8, 9]], 
               [[10, 11, 12], 
                [13, 14, 15], 
                [16, 17, 18]],
               [[19, 20, 21], 
                [22, 23, 24], 
                [25, 26, 27]]])

In [58]:
c

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

#### Again we can use the above used functions for three demensional arrays too.

In [61]:
c.shape

(3, 3, 3)

In [63]:
c.size

27

In [65]:
c.ndim

3

---
## Surprise Test
### Q. Make an three demensional array of shape '(4, 2, 2)'

In [68]:
d = np.array([[[1, 2], 
               [3, 4]], 
              [[5, 6], 
                [7, 8]], 
              [[9, 10], 
               [11, 12]],
              [[13, 14], 
               [15, 16]]])

In [70]:
d.shape

(4, 2, 2)

---
## Let's look into different functions
---

#### One can use the 'NumPy' function called 'np.ones()' to generate a matrix filled with ones as per the shape the user wants

In [74]:
np.ones((4, 6, 8))

array([[[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.,

#### One can also use the 'np.full()' function to get a matrix of the shape the user wants with a particular value filled in insted of ones.

In [77]:
np.full(shape = (9, 6), fill_value = 69)

array([[69, 69, 69, 69, 69, 69],
       [69, 69, 69, 69, 69, 69],
       [69, 69, 69, 69, 69, 69],
       [69, 69, 69, 69, 69, 69],
       [69, 69, 69, 69, 69, 69],
       [69, 69, 69, 69, 69, 69],
       [69, 69, 69, 69, 69, 69],
       [69, 69, 69, 69, 69, 69],
       [69, 69, 69, 69, 69, 69]])

#### One can make a identity matrix with function 'np.identity()'.

In [81]:
np.identity(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

#### Make random numbers whenever you need out of thin air using 'np.random()'

In [84]:
np.random.rand(4,5)

array([[0.17651221, 0.74408285, 0.37844594, 0.0887992 , 0.6519609 ],
       [0.58665856, 0.34106701, 0.81831537, 0.91561618, 0.12603007],
       [0.06684351, 0.18995118, 0.5577266 , 0.85482506, 0.15724444],
       [0.54977914, 0.07025089, 0.28742101, 0.1380842 , 0.56452762]])

#### Usually it returns floats but you can also assign it to only return integers within a specified range

In [88]:
np.random.randint(1, 14, size = (5, 5))

array([[10,  9, 12,  9,  2],
       [ 6,  9,  4,  7,  9],
       [ 4,  6,  3,  3,  6],
       [ 5, 11,  9, 12, 12],
       [ 2, 12,  2, 11, 13]])

#### If you are tired of constanly getting random numbers you can also seed the random fuction to always return a particular random generation.

In [91]:
np.random.seed(2132004)
set_seed = np.random.randn(7,)
set_seed

array([-0.61912682, -0.69934479,  0.28098204, -0.21230185, -0.73133961,
        0.91127451, -0.31879833])

## Slicing Task / Homework
#### Q. Generate a matrix of shape (3, 3) with only integres where you later on slice the matrix in such a way that it only prints each of it's quadrants

In [116]:
e = np.random.randint(1, 21, size = (3, 3))
e

array([[11, 12,  2],
       [ 9, 12,  3],
       [12, 19,  2]])

In [114]:
print(f'First quadrant: \n{e[:2, :2]}\n')
print(f'Second quadrant: \n{e[:2, 1:3]}\n')
print(f'Third quadrant: \n{e[1:, :2]}\n')
print(f'Fourth quadrant: \n{e[1:, 1:3]}')

First quadrant: 
[[ 2 19]
 [20 18]]

Second quadrant: 
[[19  6]
 [18  9]]

Third quadrant: 
[[20 18]
 [ 7 12]]

Fourth quadrant: 
[[18  9]
 [12  1]]


# The End